name: Build and Test

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: integration
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Build ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Set release info
      id: info
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        echo "::set-output name=version::$(date +"0.%V.%j")"
    - name: Run lint
      run: npm run lint
      env:
        API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
        RELEASE_BUILD: ${{ github.run_number }}
        RELEASE_SHA: ${{ steps.info.outputs.sha_short }}
        RELEASE_VERSION: ${{ steps.info.outputs.version }}
        ENVIRONMENT_NAME: integration
        DISPLAY: 3030
    - name: Run tests
      run: npm test
    