name: Deployment

on:
  push:
    branches: [ main ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: integration
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ARMADA_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.ARMADA_SECRET_ACCESS_KEY }}
        aws-region: ca-central-1
    - name: Build ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: export RELEASE_VERSION=`date +"0.%V.%j"`
    - run: npm run build
      env:
        API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
        RELEASE_BUILD: $GITHUB_RUN_NUMBER
        RELEASE_SHA: $GITHUB_SHA
    - name: Copy files to S3 bucket
      run:
        aws s3 sync out s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
