name: Deployment

on:
  push:
    branches: [ main ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: integration
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ARMADA_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.ARMADA_SECRET_ACCESS_KEY }}
        aws-region: ca-central-1
    - name: Build ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Set release info
      id: info
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        echo "::set-output name=version::$(date +"0.%V.%j")"
    - run: npm run build
      env:
        API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
        RELEASE_BUILD: ${{ github.run_number }}
        RELEASE_SHA: ${{ steps.info.outputs.sha_short }}
        RELEASE_VERSION: ${{ steps.info.outputs.version }}
    - name: Copy files to S3 bucket
      run:
        aws s3 sync out s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
    - name: Cloudfront invalidation
      run:
        aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CF_DIST_ID }} --paths "/"
